
project_id = "vczxurigjttwxwilosjz"

[functions.claude-chat]
verify_jwt = true

[functions.gemini-chat]
verify_jwt = true

[functions.send-telegram-message]
verify_jwt = false

[functions.sync-model-pricing]
verify_jwt = true

[functions.mistral-chat]
verify_jwt = true

[functions.perplexity-chat]
verify_jwt = true
