
project_id = "vczxurigjttwxwilosjz"

[functions.claude-chat]
verify_jwt = true

[functions.gemini-chat]
verify_jwt = true

[functions.send-telegram-message]
verify_jwt = false

[functions.sync-model-pricing]
verify_jwt = true

[functions.mistral-chat]
verify_jwt = true

[functions.perplexity-chat]
verify_jwt = true

[functions.qwen-chat]
verify_jwt = true


[functions.profile-demo]
verify_jwt = true

[functions.lemonsqueezy-webhook]
verify_jwt = false

[functions.multi-image-generate]
verify_jwt = true

[functions.generate-chat-title]
verify_jwt = true

[functions.mcp]
verify_jwt = false

[functions.agent-mcp]
verify_jwt = false
