// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: agent-mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-models.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.49.8";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function callChatFunction(ctx, fn, body) {
  const token = ctx.getToken();
  if (!token) throw new Error("callChatFunction requires a verified OAuth token");
  const res = await fetch(`${supabaseProjectUrl()}/functions/v1/${fn}`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
      apikey: supabasePublishableKey()
    },
    body: JSON.stringify(body)
  });
  const json = await res.json().catch(() => ({}));
  if (!res.ok || json.error) throw new Error(json.error ?? `Model request failed (${res.status})`);
  if (typeof json.content !== "string") throw new Error("Model returned no content");
  return json.content;
}

// src/lib/mcp/tools/list-models.ts
var list_models_default = defineTool({
  name: "list_models",
  title: "List models",
  description: "List the AI models available in this app, grouped by provider (OpenAI, Anthropic, Google, xAI, DeepSeek, Mistral, Perplexity, Qwen, NVIDIA), with their token cost tier.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("model_pricing").select("platform, model_id, cost_tier, tokens_per_message").order("platform", { ascending: true }).order("model_id", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const models = data ?? [];
    const lines = models.map(
      (m) => `${m.platform} \xB7 ${m.model_id} (${m.cost_tier}, ~${m.tokens_per_message} tokens/message)`
    );
    return {
      content: [{ type: "text", text: lines.join("\n") || "No models configured." }],
      structuredContent: { models }
    };
  }
});

// src/lib/mcp/tools/list-chats.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";
var list_chats_default = defineTool2({
  name: "list_chats",
  title: "List chats",
  description: "List the signed-in user's most recent conversations, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("How many conversations to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("conversations").select("id, title, chat_mode, conductor_platform, updated_at, created_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const chats = data ?? [];
    const text = chats.length ? chats.map((c) => `${c.id} \xB7 ${c.title} [${c.chat_mode}] updated ${c.updated_at}`).join("\n") : "No conversations yet.";
    return { content: [{ type: "text", text }], structuredContent: { chats } };
  }
});

// src/lib/mcp/tools/get-chat.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_chat_default = defineTool3({
  name: "get_chat",
  title: "Get chat messages",
  description: "Read the messages of one of the signed-in user's conversations, including which AI platform produced each reply.",
  inputSchema: {
    chat_id: z2.string().uuid().describe("The conversation id, as returned by list_chats."),
    limit: z2.number().int().min(1).max(200).optional().describe("How many messages to return (default 50, newest last).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ chat_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("messages").select("id, sender, platform, content, created_at").eq("conversation_id", chat_id).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const messages = (data ?? []).slice().reverse();
    if (messages.length === 0) {
      return {
        content: [{ type: "text", text: "No messages found for that conversation (or it isn't yours)." }],
        structuredContent: { messages: [] }
      };
    }
    const text = messages.map((m) => `[${m.sender}${m.platform ? `/${m.platform}` : ""}] ${m.content}`).join("\n\n");
    return { content: [{ type: "text", text }], structuredContent: { messages } };
  }
});

// src/lib/mcp/tools/search-messages.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var search_messages_default = defineTool4({
  name: "search_messages",
  title: "Search messages",
  description: "Full-text-ish search across the signed-in user's chat messages, newest first.",
  inputSchema: {
    query: z3.string().trim().min(2).describe("Text to look for inside message content."),
    limit: z3.number().int().min(1).max(50).optional().describe("How many matches to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("messages").select("id, conversation_id, sender, platform, content, created_at").ilike("content", `%${query.replace(/[%_]/g, "")}%`).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const matches = data ?? [];
    const text = matches.length ? matches.map(
      (m) => `${m.conversation_id} \xB7 [${m.sender}${m.platform ? `/${m.platform}` : ""}] ${m.content.slice(0, 300)}`
    ).join("\n\n") : `No messages matching "${query}".`;
    return { content: [{ type: "text", text }], structuredContent: { matches } };
  }
});

// src/lib/mcp/tools/ask-model.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var PLATFORM_TO_FN = {
  openai: "openai-chat",
  anthropic: "claude-chat",
  google: "gemini-chat",
  grok: "grok-chat",
  deepseek: "deepseek-chat",
  perplexity: "perplexity-chat",
  mistral: "mistral-chat",
  qwen: "qwen-chat",
  nvidia: "nvidia-chat"
};
var ask_model_default = defineTool5({
  name: "ask_model",
  title: "Ask a model",
  description: "Send a prompt to one of the app's AI providers and return its answer. Consumes the signed-in user's tokens. Use list_models to discover valid model ids.",
  inputSchema: {
    platform: z4.enum(["openai", "anthropic", "google", "grok", "deepseek", "perplexity", "mistral", "qwen", "nvidia"]).describe("Which provider to route the prompt to."),
    prompt: z4.string().trim().min(1).describe("The user prompt to send."),
    model: z4.string().trim().min(1).optional().describe("Optional explicit model id; the provider default is used otherwise."),
    system: z4.string().trim().min(1).optional().describe("Optional system instruction.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async ({ platform, prompt, model, system }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const messages = [
      ...system ? [{ role: "system", content: system }] : [],
      { role: "user", content: prompt }
    ];
    try {
      const content = await callChatFunction(ctx, PLATFORM_TO_FN[platform], {
        messages,
        ...model ? { model } : {}
      });
      return { content: [{ type: "text", text: content }], structuredContent: { platform, model, content } };
    } catch (e) {
      return {
        content: [{ type: "text", text: e instanceof Error ? e.message : String(e) }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "vczxurigjttwxwilosjz";
var mcp_default = defineMcp({
  name: "chatter-ai-voyage",
  title: "chatter-ai-voyage",
  version: "0.1.0",
  instructions: "Tools for RoboHeard, a multi-model AI orchestrator. Use list_models to see available providers and model ids, list_chats/get_chat/search_messages to read the signed-in user's conversation history, and ask_model to route a prompt to a specific provider (this consumes the user's tokens).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_models_default, list_chats_default, get_chat_default, search_messages_default, ask_model_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "agent-mcp" }));
