// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: agent-mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-models.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.49.8";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function callChatFunction(ctx, fn, body) {
  const token = ctx.getToken();
  if (!token) throw new Error("callChatFunction requires a verified OAuth token");
  const res = await fetch(`${supabaseProjectUrl()}/functions/v1/${fn}`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
      apikey: supabasePublishableKey()
    },
    body: JSON.stringify(body)
  });
  const json = await res.json().catch(() => ({}));
  if (!res.ok || json.error) throw new Error(json.error ?? `Model request failed (${res.status})`);
  if (typeof json.content !== "string") throw new Error("Model returned no content");
  return json.content;
}

// src/lib/mcp/platforms.ts
var PLATFORM_IDS = [
  "openai",
  "anthropic",
  "google",
  "grok",
  "deepseek",
  "perplexity",
  "mistral",
  "qwen",
  "nvidia"
];
var PLATFORM_TO_FN = {
  openai: "openai-chat",
  anthropic: "claude-chat",
  google: "gemini-chat",
  grok: "grok-chat",
  deepseek: "deepseek-chat",
  perplexity: "perplexity-chat",
  mistral: "mistral-chat",
  qwen: "qwen-chat",
  nvidia: "nvidia-chat"
};
var DEFAULT_MODELS = {
  openai: "gpt-4o-mini",
  anthropic: "claude-3-5-sonnet-20241022",
  google: "gemini-2.0-flash",
  grok: "grok-2-1212",
  deepseek: "deepseek-chat",
  perplexity: "sonar-pro",
  mistral: "mistral-small-latest",
  qwen: "qwen-plus",
  nvidia: "nvidia/nemotron-3-nano-30b-a3b"
};
var CAPABILITY_MATRIX = {
  openai: { think: true, search: true, deep_research: true, code_exec: true },
  anthropic: { think: true, search: true, deep_research: true, code_exec: true },
  google: { think: true, search: true, deep_research: true, code_exec: true },
  grok: { think: true, search: true, deep_research: true, code_exec: false },
  deepseek: { think: true, search: false, deep_research: true, code_exec: false },
  perplexity: { think: true, search: true, deep_research: true, code_exec: false },
  mistral: { think: false, search: false, deep_research: false, code_exec: false },
  qwen: { think: false, search: false, deep_research: false, code_exec: false },
  nvidia: { think: true, search: false, deep_research: false, code_exec: false }
};

// src/lib/mcp/runtime.ts
var ALL_TOOL_NAMES = [
  "list_models",
  "list_chats",
  "get_chat",
  "search_messages",
  "ask_model",
  "web_search",
  "conductor_ask",
  "conductor_route",
  "conductor_compare",
  "conductor_debate"
];
var DEFAULT_SETTINGS = {
  enabledTools: [...ALL_TOOL_NAMES],
  enabledPlatforms: [...PLATFORM_IDS],
  defaultConductorPlatform: "openai",
  defaultWebSearchModel: "sonar-pro"
};
async function loadMcpSettings(ctx) {
  const supabase = supabaseForUser(ctx);
  const { data } = await supabase.from("user_mcp_settings").select("enabled_tools, enabled_platforms, default_conductor_platform, default_web_search_model").eq("user_id", ctx.getUserId()).maybeSingle();
  if (!data) return DEFAULT_SETTINGS;
  const row = data;
  return {
    enabledTools: row.enabled_tools ?? [...ALL_TOOL_NAMES],
    enabledPlatforms: row.enabled_platforms ?? [...PLATFORM_IDS],
    defaultConductorPlatform: row.default_conductor_platform ?? "openai",
    defaultWebSearchModel: row.default_web_search_model ?? "sonar-pro"
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}
async function guard(ctx, toolName) {
  if (!ctx.isAuthenticated()) {
    return { error: errorResult("Not authenticated"), settings: DEFAULT_SETTINGS };
  }
  const settings = await loadMcpSettings(ctx);
  if (!settings.enabledTools.includes(toolName)) {
    return {
      error: errorResult(`Tool "${toolName}" is disabled in your MCP settings. Enable it at /mcp in RoboHeard.`),
      settings
    };
  }
  return { error: null, settings };
}
function assertPlatformAllowed(settings, platform) {
  if (!settings.enabledPlatforms.includes(platform)) {
    throw new Error(`Platform "${platform}" is disabled in your MCP settings.`);
  }
}
async function ensureConversation(ctx, opts) {
  if (opts.conversationId) return opts.conversationId;
  const supabase = supabaseForUser(ctx);
  const { data, error } = await supabase.from("conversations").insert({
    user_id: ctx.getUserId(),
    title: opts.title,
    chat_mode: opts.chatMode,
    conductor_platform: opts.conductorPlatform ?? null
  }).select("id").single();
  if (error || !data) throw new Error(`Failed to create conversation: ${error?.message}`);
  return data.id;
}
async function saveMessage(ctx, conversationId, sender, content, platform) {
  const supabase = supabaseForUser(ctx);
  await supabase.from("messages").insert({
    conversation_id: conversationId,
    sender,
    content,
    platform: platform ?? null
  });
}
async function loadHistory(ctx, conversationId) {
  const supabase = supabaseForUser(ctx);
  const { data } = await supabase.from("messages").select("sender, content").eq("conversation_id", conversationId).order("created_at", { ascending: true });
  return (data ?? []).map((m) => ({
    role: m.sender === "user" ? "user" : "assistant",
    content: m.content
  }));
}

// src/lib/mcp/tools/list-models.ts
var list_models_default = defineTool({
  name: "list_models",
  title: "List available models",
  description: "List RoboHeard's AI platforms (OpenAI, Anthropic, Google, xAI, DeepSeek, Mistral, Perplexity, Qwen, NVIDIA), their model ids and cost tiers, and which advanced capabilities (think, search, deep_research, code_exec) each supports. Call first to discover what to route to.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const g = await guard(ctx, "list_models");
    if (g.error) return g.error;
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("model_pricing").select("platform, model_id, cost_tier, tokens_per_message").order("platform", { ascending: true }).order("model_id", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const byPlatform = {};
    for (const row of rows) (byPlatform[row.platform] ??= []).push(row);
    const platforms = PLATFORM_IDS.filter((id) => g.settings.enabledPlatforms.includes(id)).map((id) => ({
      id,
      default_model: DEFAULT_MODELS[id],
      capabilities: CAPABILITY_MATRIX[id],
      models: (byPlatform[id] ?? []).map((m) => ({
        model_id: m.model_id,
        cost_tier: m.cost_tier,
        tokens_per_message: m.tokens_per_message
      }))
    }));
    return jsonResult({ platforms, enabled_tools: g.settings.enabledTools });
  }
});

// src/lib/mcp/tools/list-chats.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";
var list_chats_default = defineTool2({
  name: "list_chats",
  title: "List chats",
  description: "List the signed-in user's most recent conversations, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("How many conversations to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    const g = await guard(ctx, "list_chats");
    if (g.error) return g.error;
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("conversations").select("id, title, chat_mode, conductor_platform, updated_at, created_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const chats = data ?? [];
    const text = chats.length ? chats.map((c) => `${c.id} \xB7 ${c.title} [${c.chat_mode}] updated ${c.updated_at}`).join("\n") : "No conversations yet.";
    return { content: [{ type: "text", text }], structuredContent: { chats } };
  }
});

// src/lib/mcp/tools/get-chat.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_chat_default = defineTool3({
  name: "get_chat",
  title: "Get chat messages",
  description: "Read the messages of one of the signed-in user's conversations, including which AI platform produced each reply.",
  inputSchema: {
    chat_id: z2.string().uuid().describe("The conversation id, as returned by list_chats."),
    limit: z2.number().int().min(1).max(200).optional().describe("How many messages to return (default 50, newest last).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ chat_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("messages").select("id, sender, platform, content, created_at").eq("conversation_id", chat_id).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const messages = (data ?? []).slice().reverse();
    if (messages.length === 0) {
      return {
        content: [{ type: "text", text: "No messages found for that conversation (or it isn't yours)." }],
        structuredContent: { messages: [] }
      };
    }
    const text = messages.map((m) => `[${m.sender}${m.platform ? `/${m.platform}` : ""}] ${m.content}`).join("\n\n");
    return { content: [{ type: "text", text }], structuredContent: { messages } };
  }
});

// src/lib/mcp/tools/search-messages.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var search_messages_default = defineTool4({
  name: "search_messages",
  title: "Search messages",
  description: "Full-text-ish search across the signed-in user's chat messages, newest first.",
  inputSchema: {
    query: z3.string().trim().min(2).describe("Text to look for inside message content."),
    limit: z3.number().int().min(1).max(50).optional().describe("How many matches to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("messages").select("id, conversation_id, sender, platform, content, created_at").ilike("content", `%${query.replace(/[%_]/g, "")}%`).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const matches = data ?? [];
    const text = matches.length ? matches.map(
      (m) => `${m.conversation_id} \xB7 [${m.sender}${m.platform ? `/${m.platform}` : ""}] ${m.content.slice(0, 300)}`
    ).join("\n\n") : `No messages matching "${query}".`;
    return { content: [{ type: "text", text }], structuredContent: { matches } };
  }
});

// src/lib/mcp/tools/ask-model.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var ask_model_default = defineTool5({
  name: "ask_model",
  title: "Ask a single AI model",
  description: "Send a prompt to ONE AI model through RoboHeard \u2014 fastest and cheapest path. Optionally enable advanced capabilities (think, search, deep_research, code_exec) and continue an existing conversation. Consumes the signed-in user's tokens and persists to chat history. Use list_models to discover valid model ids.",
  inputSchema: {
    platform: z4.enum(PLATFORM_IDS).describe("Which provider to route the prompt to."),
    prompt: z4.string().trim().min(1).describe("The user prompt to send."),
    model: z4.string().trim().min(1).optional().describe("Optional explicit model id; the platform default is used otherwise."),
    system: z4.string().trim().min(1).optional().describe("Optional system instruction."),
    capabilities: z4.object({
      think: z4.boolean().optional(),
      search: z4.boolean().optional(),
      deep_research: z4.boolean().optional(),
      code_exec: z4.boolean().optional()
    }).optional().describe("Advanced capabilities to enable for supported models."),
    conversation_id: z4.string().uuid().optional().describe("Optional existing RoboHeard conversation to continue.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async ({ platform, prompt, model, system, capabilities, conversation_id }, ctx) => {
    const g = await guard(ctx, "ask_model");
    if (g.error) return g.error;
    try {
      assertPlatformAllowed(g.settings, platform);
      const chosenModel = model ?? DEFAULT_MODELS[platform];
      const conversationId = await ensureConversation(ctx, {
        conversationId: conversation_id,
        title: prompt.slice(0, 60),
        chatMode: "free"
      });
      const history = conversation_id ? await loadHistory(ctx, conversationId) : [];
      await saveMessage(ctx, conversationId, "user", prompt);
      const messages = [
        ...system ? [{ role: "system", content: system }] : [],
        ...history,
        { role: "user", content: prompt }
      ];
      const content = await callChatFunction(ctx, PLATFORM_TO_FN[platform], {
        messages,
        model: chosenModel,
        ...capabilities ? { capabilities } : {}
      });
      await saveMessage(ctx, conversationId, "ai", content, platform);
      return jsonResult({ platform, model: chosenModel, conversation_id: conversationId, content });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "vczxurigjttwxwilosjz";
var mcp_default = defineMcp({
  name: "chatter-ai-voyage",
  title: "chatter-ai-voyage",
  version: "0.1.0",
  instructions: "Tools for RoboHeard, a multi-model AI orchestrator. Use list_models to see available providers and model ids, list_chats/get_chat/search_messages to read the signed-in user's conversation history, and ask_model to route a prompt to a specific provider (this consumes the user's tokens).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_models_default, list_chats_default, get_chat_default, search_messages_default, ask_model_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "agent-mcp" }));
