// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: agent-mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-models.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.49.8";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function callChatFunction(ctx, fn, body) {
  const token = ctx.getToken();
  if (!token) throw new Error("callChatFunction requires a verified OAuth token");
  const res = await fetch(`${supabaseProjectUrl()}/functions/v1/${fn}`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
      apikey: supabasePublishableKey()
    },
    body: JSON.stringify(body)
  });
  const json = await res.json().catch(() => ({}));
  if (!res.ok || json.error) throw new Error(json.error ?? `Model request failed (${res.status})`);
  if (typeof json.content !== "string") throw new Error("Model returned no content");
  return json.content;
}

// src/lib/mcp/platforms.ts
var PLATFORM_IDS = [
  "openai",
  "anthropic",
  "google",
  "grok",
  "deepseek",
  "perplexity",
  "mistral",
  "qwen",
  "nvidia"
];
var PLATFORM_TO_FN = {
  openai: "openai-chat",
  anthropic: "claude-chat",
  google: "gemini-chat",
  grok: "grok-chat",
  deepseek: "deepseek-chat",
  perplexity: "perplexity-chat",
  mistral: "mistral-chat",
  qwen: "qwen-chat",
  nvidia: "nvidia-chat"
};
var DEFAULT_MODELS = {
  openai: "gpt-5.6-terra",
  anthropic: "claude-sonnet-5",
  google: "gemini-3.6-flash",
  grok: "grok-4.3",
  deepseek: "deepseek-chat",
  perplexity: "sonar-pro",
  mistral: "mistral-medium-3.5",
  qwen: "qwen3.6-plus",
  nvidia: "nvidia/nemotron-3-nano-30b-a3b"
};
var CAPABILITY_MATRIX = {
  openai: { think: true, search: true, deep_research: true, code_exec: true },
  anthropic: { think: true, search: true, deep_research: true, code_exec: true },
  google: { think: true, search: true, deep_research: true, code_exec: true },
  grok: { think: true, search: true, deep_research: true, code_exec: false },
  deepseek: { think: true, search: false, deep_research: true, code_exec: false },
  perplexity: { think: true, search: true, deep_research: true, code_exec: false },
  mistral: { think: true, search: false, deep_research: false, code_exec: true },
  qwen: { think: true, search: true, deep_research: false, code_exec: false },
  nvidia: { think: true, search: false, deep_research: false, code_exec: false }
};

// src/lib/mcp/runtime.ts
var ALL_TOOL_NAMES = [
  "list_models",
  "list_chats",
  "get_chat",
  "search_messages",
  "ask_model",
  "web_search",
  "conductor_ask",
  "conductor_route",
  "conductor_compare",
  "conductor_debate"
];
var DEFAULT_SETTINGS = {
  enabledTools: [...ALL_TOOL_NAMES],
  enabledPlatforms: [...PLATFORM_IDS],
  defaultConductorPlatform: "openai",
  defaultWebSearchModel: "sonar-pro"
};
async function loadMcpSettings(ctx) {
  const supabase = supabaseForUser(ctx);
  const { data } = await supabase.from("user_mcp_settings").select("enabled_tools, enabled_platforms, default_conductor_platform, default_web_search_model").eq("user_id", ctx.getUserId()).maybeSingle();
  if (!data) return DEFAULT_SETTINGS;
  const row = data;
  return {
    enabledTools: row.enabled_tools ?? [...ALL_TOOL_NAMES],
    enabledPlatforms: row.enabled_platforms ?? [...PLATFORM_IDS],
    defaultConductorPlatform: row.default_conductor_platform ?? "openai",
    defaultWebSearchModel: row.default_web_search_model ?? "sonar-pro"
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}
async function guard(ctx, toolName) {
  if (!ctx.isAuthenticated()) {
    return { error: errorResult("Not authenticated"), settings: DEFAULT_SETTINGS };
  }
  const settings = await loadMcpSettings(ctx);
  if (!settings.enabledTools.includes(toolName)) {
    return {
      error: errorResult(`Tool "${toolName}" is disabled in your MCP settings. Enable it at /mcp in RoboHeard.`),
      settings
    };
  }
  return { error: null, settings };
}
function assertPlatformAllowed(settings, platform) {
  if (!settings.enabledPlatforms.includes(platform)) {
    throw new Error(`Platform "${platform}" is disabled in your MCP settings.`);
  }
}
function allowedPanel(settings, conductor, include) {
  const requested = (include ?? []).filter(
    (p) => settings.enabledPlatforms.includes(p)
  );
  if (requested.length > 0) return requested;
  return settings.enabledPlatforms.filter((p) => p !== conductor).slice(0, 4);
}
async function ensureConversation(ctx, opts) {
  if (opts.conversationId) return opts.conversationId;
  const supabase = supabaseForUser(ctx);
  const { data, error } = await supabase.from("conversations").insert({
    user_id: ctx.getUserId(),
    title: opts.title,
    chat_mode: opts.chatMode,
    conductor_platform: opts.conductorPlatform ?? null
  }).select("id").single();
  if (error || !data) throw new Error(`Failed to create conversation: ${error?.message}`);
  return data.id;
}
async function saveMessage(ctx, conversationId, sender, content, platform) {
  const supabase = supabaseForUser(ctx);
  await supabase.from("messages").insert({
    conversation_id: conversationId,
    sender,
    content,
    platform: platform ?? null
  });
}
async function loadHistory(ctx, conversationId) {
  const supabase = supabaseForUser(ctx);
  const { data } = await supabase.from("messages").select("sender, content").eq("conversation_id", conversationId).order("created_at", { ascending: true });
  return (data ?? []).map((m) => ({
    role: m.sender === "user" ? "user" : "assistant",
    content: m.content
  }));
}
async function runConductorRound(ctx, opts) {
  const { conversationId, prompt, conductorPlatform, panel } = opts;
  const decisionPrompt = `You are the Conductor coordinating multiple AI agents.
User message: "${prompt}"
Available agents: ${panel.join(", ")}
Provide a brief coordination plan, then respond. Add [COORDINATION_NEEDED: YES] to trigger multi-agent fan-out, or [COORDINATION_NEEDED: NO] to answer solo.`;
  const decision = await callChatFunction(ctx, PLATFORM_TO_FN[conductorPlatform], {
    messages: [{ role: "user", content: decisionPrompt }],
    model: DEFAULT_MODELS[conductorPlatform]
  });
  await saveMessage(ctx, conversationId, "ai", decision, conductorPlatform);
  const needsFanout = !/\[COORDINATION_NEEDED:\s*NO\s*\]/i.test(decision);
  if (!needsFanout || panel.length === 0) {
    return { decision, agent_responses: [], synthesis: decision };
  }
  const coordinationPrompt = `The Conductor asked for your perspective on: "${prompt}"

Conductor's plan: ${decision}

Provide your specialized angle.`;
  const settled = await Promise.allSettled(
    panel.map(async (p) => ({
      platform: p,
      content: await callChatFunction(ctx, PLATFORM_TO_FN[p], {
        messages: [{ role: "user", content: coordinationPrompt }],
        model: DEFAULT_MODELS[p]
      })
    }))
  );
  const agentResponses = settled.filter((r) => r.status === "fulfilled").map((r) => r.value);
  for (const ar of agentResponses) {
    await saveMessage(ctx, conversationId, "ai", ar.content, ar.platform);
  }
  if (agentResponses.length === 0) return { decision, agent_responses: [], synthesis: decision };
  const synthesisPrompt = `Synthesize these agent responses into one coherent answer for the user.

Original question: "${prompt}"

${agentResponses.map((a) => `[${a.platform}]:
${a.content}`).join("\n\n")}

Provide the best synthesized answer.`;
  const synthesis = await callChatFunction(ctx, PLATFORM_TO_FN[conductorPlatform], {
    messages: [{ role: "user", content: synthesisPrompt }],
    model: DEFAULT_MODELS[conductorPlatform]
  });
  await saveMessage(ctx, conversationId, "ai", synthesis, conductorPlatform);
  return { decision, agent_responses: agentResponses, synthesis };
}

// src/lib/mcp/tools/list-models.ts
var list_models_default = defineTool({
  name: "list_models",
  title: "List available models",
  description: "List RoboHeard's AI platforms (OpenAI, Anthropic, Google, xAI, DeepSeek, Mistral, Perplexity, Qwen, NVIDIA), their model ids and cost tiers, and which advanced capabilities (think, search, deep_research, code_exec) each supports. Call first to discover what to route to.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const g = await guard(ctx, "list_models");
    if (g.error) return g.error;
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("model_pricing").select("platform, model_id, cost_tier, tokens_per_message").order("platform", { ascending: true }).order("model_id", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const byPlatform = {};
    for (const row of rows) (byPlatform[row.platform] ??= []).push(row);
    const platforms = PLATFORM_IDS.filter((id) => g.settings.enabledPlatforms.includes(id)).map((id) => ({
      id,
      default_model: DEFAULT_MODELS[id],
      capabilities: CAPABILITY_MATRIX[id],
      models: (byPlatform[id] ?? []).map((m) => ({
        model_id: m.model_id,
        cost_tier: m.cost_tier,
        tokens_per_message: m.tokens_per_message
      }))
    }));
    return jsonResult({ platforms, enabled_tools: g.settings.enabledTools });
  }
});

// src/lib/mcp/tools/list-chats.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";
var list_chats_default = defineTool2({
  name: "list_chats",
  title: "List chats",
  description: "List the signed-in user's most recent conversations, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("How many conversations to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    const g = await guard(ctx, "list_chats");
    if (g.error) return g.error;
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("conversations").select("id, title, chat_mode, conductor_platform, updated_at, created_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const chats = data ?? [];
    const text = chats.length ? chats.map((c) => `${c.id} \xB7 ${c.title} [${c.chat_mode}] updated ${c.updated_at}`).join("\n") : "No conversations yet.";
    return { content: [{ type: "text", text }], structuredContent: { chats } };
  }
});

// src/lib/mcp/tools/get-chat.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_chat_default = defineTool3({
  name: "get_chat",
  title: "Get chat messages",
  description: "Read the messages of one of the signed-in user's conversations, including which AI platform produced each reply.",
  inputSchema: {
    chat_id: z2.string().uuid().describe("The conversation id, as returned by list_chats."),
    limit: z2.number().int().min(1).max(200).optional().describe("How many messages to return (default 50, newest last).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ chat_id, limit }, ctx) => {
    const g = await guard(ctx, "get_chat");
    if (g.error) return g.error;
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("messages").select("id, sender, platform, content, created_at").eq("conversation_id", chat_id).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const messages = (data ?? []).slice().reverse();
    if (messages.length === 0) {
      return {
        content: [{ type: "text", text: "No messages found for that conversation (or it isn't yours)." }],
        structuredContent: { messages: [] }
      };
    }
    const text = messages.map((m) => `[${m.sender}${m.platform ? `/${m.platform}` : ""}] ${m.content}`).join("\n\n");
    return { content: [{ type: "text", text }], structuredContent: { messages } };
  }
});

// src/lib/mcp/tools/search-messages.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var search_messages_default = defineTool4({
  name: "search_messages",
  title: "Search messages",
  description: "Full-text-ish search across the signed-in user's chat messages, newest first.",
  inputSchema: {
    query: z3.string().trim().min(2).describe("Text to look for inside message content."),
    limit: z3.number().int().min(1).max(50).optional().describe("How many matches to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    const g = await guard(ctx, "search_messages");
    if (g.error) return g.error;
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("messages").select("id, conversation_id, sender, platform, content, created_at").ilike("content", `%${query.replace(/[%_]/g, "")}%`).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const matches = data ?? [];
    const text = matches.length ? matches.map(
      (m) => `${m.conversation_id} \xB7 [${m.sender}${m.platform ? `/${m.platform}` : ""}] ${m.content.slice(0, 300)}`
    ).join("\n\n") : `No messages matching "${query}".`;
    return { content: [{ type: "text", text }], structuredContent: { matches } };
  }
});

// src/lib/mcp/tools/ask-model.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var ask_model_default = defineTool5({
  name: "ask_model",
  title: "Ask a single AI model",
  description: "Send a prompt to ONE AI model through RoboHeard \u2014 fastest and cheapest path. Optionally enable advanced capabilities (think, search, deep_research, code_exec) and continue an existing conversation. Consumes the signed-in user's tokens and persists to chat history. Use list_models to discover valid model ids.",
  inputSchema: {
    platform: z4.enum(PLATFORM_IDS).describe("Which provider to route the prompt to."),
    prompt: z4.string().trim().min(1).describe("The user prompt to send."),
    model: z4.string().trim().min(1).optional().describe("Optional explicit model id; the platform default is used otherwise."),
    system: z4.string().trim().min(1).optional().describe("Optional system instruction."),
    capabilities: z4.object({
      think: z4.boolean().optional(),
      search: z4.boolean().optional(),
      deep_research: z4.boolean().optional(),
      code_exec: z4.boolean().optional()
    }).optional().describe("Advanced capabilities to enable for supported models."),
    conversation_id: z4.string().uuid().optional().describe("Optional existing RoboHeard conversation to continue.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async ({ platform, prompt, model, system, capabilities, conversation_id }, ctx) => {
    const g = await guard(ctx, "ask_model");
    if (g.error) return g.error;
    try {
      assertPlatformAllowed(g.settings, platform);
      const chosenModel = model ?? DEFAULT_MODELS[platform];
      const conversationId = await ensureConversation(ctx, {
        conversationId: conversation_id,
        title: prompt.slice(0, 60),
        chatMode: "free"
      });
      const history = conversation_id ? await loadHistory(ctx, conversationId) : [];
      await saveMessage(ctx, conversationId, "user", prompt);
      const messages = [
        ...system ? [{ role: "system", content: system }] : [],
        ...history,
        { role: "user", content: prompt }
      ];
      const content = await callChatFunction(ctx, PLATFORM_TO_FN[platform], {
        messages,
        model: chosenModel,
        ...capabilities ? { capabilities } : {}
      });
      await saveMessage(ctx, conversationId, "ai", content, platform);
      return jsonResult({ platform, model: chosenModel, conversation_id: conversationId, content });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/web-search.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";
var web_search_default = defineTool6({
  name: "web_search",
  title: "Live web search with citations",
  description: "Live web search grounded in real-time results with numbered source citations, powered by Perplexity Sonar. Returns { answer, citations: [{index, url, title}], model, query }. Use for time-sensitive facts, library changelogs, docs lookups, and anything training data may not cover. Always cite the returned sources.",
  inputSchema: {
    query: z5.string().trim().min(2).describe("Search query."),
    recency: z5.enum(["day", "week", "month", "year"]).optional().describe("Only include results from the last day/week/month/year."),
    mode: z5.enum(["web", "academic", "sec"]).optional().describe("Search corpus. Defaults to web."),
    domains: z5.array(z5.string()).optional().describe("Optional allow-list of domains (e.g. ['docs.python.org']). Prefix with '-' to exclude."),
    max_results: z5.number().int().min(1).max(20).optional().describe("Approximate max sources to consider (default 8)."),
    model: z5.enum(["sonar", "sonar-pro", "sonar-reasoning", "sonar-reasoning-pro"]).optional().describe("Perplexity model. Defaults to your configured web-search model.")
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ query, recency, mode, domains, max_results, model }, ctx) => {
    const g = await guard(ctx, "web_search");
    if (g.error) return g.error;
    const key = runtimeEnv("PERPLEXITY_API_KEY");
    if (!key) return errorResult("Web search unavailable: PERPLEXITY_API_KEY is not configured on the server.");
    const chosenModel = model ?? g.settings.defaultWebSearchModel;
    const searchMode = mode ?? "web";
    const maxResults = max_results ?? 8;
    const body = {
      model: chosenModel,
      messages: [
        {
          role: "system",
          content: "You are a research assistant. Answer the user's query concisely using ONLY the retrieved web sources. Use inline numeric citations like [1], [2] tied to the citations array. Prefer authoritative and recent sources. If sources conflict, say so."
        },
        { role: "user", content: query }
      ],
      return_related_questions: false,
      max_tokens: 1500,
      web_search_options: {
        search_context_size: maxResults >= 12 ? "high" : maxResults >= 6 ? "medium" : "low"
      }
    };
    if (recency) body.search_recency_filter = recency;
    if (searchMode !== "web") body.search_mode = searchMode;
    if (domains && domains.length > 0) body.search_domain_filter = domains.slice(0, 20);
    const res = await fetch("https://api.perplexity.ai/chat/completions", {
      method: "POST",
      headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
      body: JSON.stringify(body)
    });
    if (!res.ok) {
      const errText = await res.text();
      return errorResult(`Perplexity ${res.status}: ${errText.slice(0, 400)}`);
    }
    const data = await res.json();
    const answer = String(data.choices?.[0]?.message?.content ?? "");
    const raw = data.citations ?? data.search_results ?? [];
    const citations = raw.map((c, i) => {
      const url = typeof c === "string" ? c : c?.url ?? "";
      const title = typeof c === "string" ? void 0 : c?.title;
      return { index: i + 1, url, ...title ? { title } : {} };
    }).filter((c) => c.url);
    return jsonResult({
      query,
      model: chosenModel,
      answer,
      citations,
      search_mode: searchMode,
      recency: recency ?? null
    });
  }
});

// src/lib/mcp/tools/conductor.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^4.4.3";
var platformEnum = z6.enum(PLATFORM_IDS);
var conductorAskTool = defineTool7({
  name: "conductor_ask",
  title: "Conductor \u2014 orchestrated multi-model answer",
  description: "Run RoboHeard's Conductor: one model routes the prompt across a panel of frontier AIs, collects their perspectives, and synthesizes a single best answer. Prefer this over ask_model when the question is ambiguous, high-stakes, or spans multiple domains. Persists to chat history.",
  inputSchema: {
    prompt: z6.string().trim().min(1).describe("The user prompt to route across the panel."),
    conductor_platform: platformEnum.optional().describe("Which model plays Conductor. Defaults to your configured one."),
    include_platforms: z6.array(platformEnum).optional().describe("Restrict the panel. Defaults to 4 frontier models."),
    conversation_id: z6.string().uuid().optional().describe("Optional existing conversation to continue.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async ({ prompt, conductor_platform, include_platforms, conversation_id }, ctx) => {
    const g = await guard(ctx, "conductor_ask");
    if (g.error) return g.error;
    const conductor = conductor_platform ?? g.settings.defaultConductorPlatform;
    const panel = allowedPanel(g.settings, conductor, include_platforms);
    try {
      const conversationId = await ensureConversation(ctx, {
        conversationId: conversation_id,
        title: `MCP: ${prompt.slice(0, 50)}`,
        chatMode: "conductor",
        conductorPlatform: conductor
      });
      await saveMessage(ctx, conversationId, "user", prompt);
      const round = await runConductorRound(ctx, { conversationId, prompt, conductorPlatform: conductor, panel });
      return jsonResult({ conversation_id: conversationId, conductor_platform: conductor, panel, ...round });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
  }
});
var conductorRouteTool = defineTool7({
  name: "conductor_route",
  title: "Conductor \u2014 routing plan only",
  description: "Ask the Conductor which agents SHOULD answer a prompt and why, without fanning out. Cheap \u2014 use to preview a plan before spending tokens with conductor_ask or conductor_debate.",
  inputSchema: {
    prompt: z6.string().trim().min(1).describe("The prompt to plan for."),
    conductor_platform: platformEnum.optional().describe("Which model plans the route."),
    include_platforms: z6.array(platformEnum).optional().describe("Candidate agents to choose from.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ prompt, conductor_platform, include_platforms }, ctx) => {
    const g = await guard(ctx, "conductor_route");
    if (g.error) return g.error;
    const conductor = conductor_platform ?? g.settings.defaultConductorPlatform;
    const panel = allowedPanel(g.settings, conductor, include_platforms);
    const planPrompt = `You are the RoboHeard Conductor. Do NOT answer the user's question.
Instead, return a JSON routing plan with fields:
  { "strategy": "solo"|"fanout"|"debate", "agents": string[], "reasoning": string }
where "agents" is a subset of: ${panel.join(", ")}.
User prompt: "${prompt}"
Reply with ONLY the JSON object.`;
    try {
      const raw = await callChatFunction(ctx, PLATFORM_TO_FN[conductor], {
        messages: [{ role: "user", content: planPrompt }],
        model: DEFAULT_MODELS[conductor]
      });
      let plan = raw;
      const match = raw.match(/\{[\s\S]*\}/);
      if (match) {
        try {
          plan = JSON.parse(match[0]);
        } catch {
        }
      }
      return jsonResult({ conductor_platform: conductor, panel, plan });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
  }
});
var conductorCompareTool = defineTool7({
  name: "conductor_compare",
  title: "Conductor \u2014 raw multi-model perspectives",
  description: "Fan the prompt out to the panel and return each agent's raw answer side-by-side, WITHOUT a synthesis step. Use to compare or benchmark models yourself. Cheaper than conductor_ask.",
  inputSchema: {
    prompt: z6.string().trim().min(1).describe("The prompt to send to every agent."),
    include_platforms: z6.array(platformEnum).optional().describe("Which agents to compare."),
    conversation_id: z6.string().uuid().optional().describe("Optional existing conversation to continue.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async ({ prompt, include_platforms, conversation_id }, ctx) => {
    const g = await guard(ctx, "conductor_compare");
    if (g.error) return g.error;
    const panel = allowedPanel(g.settings, g.settings.defaultConductorPlatform, include_platforms);
    if (panel.length === 0) return errorResult("No platforms are enabled in your MCP settings.");
    try {
      const conversationId = await ensureConversation(ctx, {
        conversationId: conversation_id,
        title: `MCP compare: ${prompt.slice(0, 40)}`,
        chatMode: "side-by-side"
      });
      await saveMessage(ctx, conversationId, "user", prompt);
      const settled = await Promise.allSettled(
        panel.map(async (p) => ({
          platform: p,
          model: DEFAULT_MODELS[p],
          content: await callChatFunction(ctx, PLATFORM_TO_FN[p], {
            messages: [{ role: "user", content: prompt }],
            model: DEFAULT_MODELS[p]
          })
        }))
      );
      const perspectives = settled.map(
        (r, i) => r.status === "fulfilled" ? r.value : {
          platform: panel[i],
          model: DEFAULT_MODELS[panel[i]],
          content: "",
          error: r.reason instanceof Error ? r.reason.message : String(r.reason)
        }
      );
      for (const p of perspectives) {
        if (p.content) await saveMessage(ctx, conversationId, "ai", p.content, p.platform);
      }
      return jsonResult({ conversation_id: conversationId, perspectives });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
  }
});
var conductorDebateTool = defineTool7({
  name: "conductor_debate",
  title: "Conductor \u2014 multi-round critique loop",
  description: "Run the Conductor N times in a critique-and-improve loop, ending with a final synthesized answer. Use for hard reasoning, code review, or architecture decisions. Slower and consumes more tokens.",
  inputSchema: {
    prompt: z6.string().trim().min(1).describe("The problem to work through."),
    iterations: z6.number().int().min(2).max(5).optional().describe("Number of rounds (default 3)."),
    conductor_platform: platformEnum.optional().describe("Which model plays Conductor."),
    include_platforms: z6.array(platformEnum).optional().describe("Restrict the panel."),
    conversation_id: z6.string().uuid().optional().describe("Optional existing conversation to continue.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async ({ prompt, iterations, conductor_platform, include_platforms, conversation_id }, ctx) => {
    const g = await guard(ctx, "conductor_debate");
    if (g.error) return g.error;
    const rounds = iterations ?? 3;
    const conductor = conductor_platform ?? g.settings.defaultConductorPlatform;
    const panel = allowedPanel(g.settings, conductor, include_platforms);
    try {
      const conversationId = await ensureConversation(ctx, {
        conversationId: conversation_id,
        title: `MCP debate: ${prompt.slice(0, 40)}`,
        chatMode: "conductor",
        conductorPlatform: conductor
      });
      await saveMessage(ctx, conversationId, "user", prompt);
      const results = [];
      let current = prompt;
      for (let i = 1; i <= rounds; i++) {
        const isFinal = i === rounds;
        const framed = i === 1 ? current : `Iteration ${i} of ${rounds}${isFinal ? " (FINAL)" : ""}. Prior synthesis:

${current}

Critique it, resolve gaps, and produce ${isFinal ? "the final answer" : "an improved answer"} to the original question: "${prompt}"`;
        const round = await runConductorRound(ctx, {
          conversationId,
          prompt: framed,
          conductorPlatform: conductor,
          panel
        });
        results.push({ iteration: i, synthesis: round.synthesis });
        current = round.synthesis;
      }
      return jsonResult({
        conversation_id: conversationId,
        conductor_platform: conductor,
        panel,
        iterations: results,
        final: results[results.length - 1]?.synthesis ?? ""
      });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "vczxurigjttwxwilosjz";
var mcp_default = defineMcp({
  name: "chatter-ai-voyage",
  title: "chatter-ai-voyage",
  version: "0.2.0",
  instructions: "RoboHeard MCP \u2014 multi-model orchestration. Discovery: call list_models first. Single model: ask_model (supports think/search/deep_research/code_exec capabilities). Live web facts with citations: web_search. Orchestrated reasoning: conductor_route (plan only), conductor_compare (raw side-by-side perspectives), conductor_ask (routed + synthesized answer), conductor_debate (multi-round critique loop). History: list_chats, get_chat, search_messages. Every call runs as the signed-in user, spends their RoboHeard tokens, and appears in their RoboHeard sidebar. Tool availability, platforms, and defaults follow the user's MCP settings at /mcp.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_models_default,
    list_chats_default,
    get_chat_default,
    search_messages_default,
    ask_model_default,
    web_search_default,
    conductorRouteTool,
    conductorCompareTool,
    conductorAskTool,
    conductorDebateTool
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "agent-mcp" }));
