
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vczxurigjttwxwilosjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjenh1cmlnanR0d3h3aWxvc2p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MDUwMTYsImV4cCI6MjA2NDA4MTAxNn0.8LTD0Ju6cfnai5fyo57Ydmq3FpMrImlQDGK2Nc-SD3o";

// Validate configuration
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Missing Supabase configuration:', {
    url: !!SUPABASE_URL,
    key: !!SUPABASE_PUBLISHABLE_KEY
  });
  throw new Error('Missing Supabase configuration');
}

console.log('Supabase client configuration:', {
  url: SUPABASE_URL,
  hasKey: !!SUPABASE_PUBLISHABLE_KEY
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  },
  global: {
    headers: {
      'X-Client-Info': 'roboheard-web-client'
    }
  },
  // Add retry logic for network issues
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});

// Add error logging for debugging
supabase.auth.onAuthStateChange((event, session) => {
  console.log('Supabase auth state change:', {
    event,
    hasSession: !!session,
    userId: session?.user?.id,
    email: session?.user?.email
  });
});

// Test basic connectivity with proper error handling and retry logic
const testConnectivity = async (retries = 3) => {
  for (let i = 0; i < retries; i++) {
    try {
      console.log(`Supabase connectivity test attempt ${i + 1}/${retries}`);
      const result = await supabase.from('profiles').select('count').limit(1);
      console.log('Supabase connectivity test:', result.error ? 'Failed' : 'Success', result.error);
      
      if (!result.error) {
        break; // Success, exit retry loop
      }
      
      if (i < retries - 1) {
        console.log(`Retrying in ${(i + 1) * 1000}ms...`);
        await new Promise(resolve => setTimeout(resolve, (i + 1) * 1000));
      }
    } catch (error) {
      console.error(`Supabase connectivity test failed (attempt ${i + 1}):`, error);
      
      if (i < retries - 1) {
        console.log(`Retrying in ${(i + 1) * 1000}ms...`);
        await new Promise(resolve => setTimeout(resolve, (i + 1) * 1000));
      }
    }
  }
};

// Only test connectivity in browser environment
if (typeof window !== 'undefined') {
  testConnectivity();
}
